CREATE TABLE register_ovni
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location    VARCHAR(255),
    date        TIMESTAMP NOT NULL,
    color       VARCHAR(255),
    shape       shape_enum NOT NULL, 
    quantity    INT NOT NULL

);