
CREATE TYPE shape_enum AS ENUM ('Disc', 'Sphere', 'Triangle', 'Other');

CREATE TABLE register_ovni
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location    VARCHAR(255),
    local_date_time        TIMESTAMP NOT NULL,
    color       VARCHAR(255),
    shape_enum       shape_enum NOT NULL, 
    quantity    INT NOT NULL

);